default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: booking_development
  host: <%= ENV['DB_PORT_5432_TCP_ADDR'] %>
  username: postgres

test:
  <<: *default
  database: booking_test
  host: <%= ENV['DB_PORT_5432_TCP_ADDR'] %>
  username: postgres

production:
  <<: *default
  database: booking_production
  username: booking
  password: <%= ENV['BOOKING_DATABASE_PASSWORD'] %>
